export const TYPES = {
  LOGIN: 'LOGIN',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  LOGOUT: 'LOGOUT',
  ADD_FAVORITE_POKEMON: 'ADD_FAVORITE_POKEMON',
  REMOVE_FAVORITE_POKEMON: 'REMOVE_FAVORITE_POKEMON'
}